# This is the configuration used to check the rubocop source code.
inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  DisabledByDefault: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.0
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/fet_geo_percentages_load_db.rake'

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/PluralizationGrammar:
  Enabled: false

# doesnt seem to work with modal_action
Rails/LexicallyScopedActionFilter:
  Enabled: false

# to be enabled
Rails/FilePath:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/Present:
  Enabled: false
Rails/Validation:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/RequestReferer:
  Enabled: false
Rails/Presence:
  Enabled: false
Rails/Blank:
  Enabled: false
Style/GuardClause:
  Enabled: false
# end to be enabled

Rails/FindBy:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: true

Rails/ActionFilter:
  EnforcedStyle: action

Rails/HttpPositionalArguments:
  Enabled: true

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/IndentationWidth:
  IgnoredPatterns: ['^\s*private','^\s*protected']

# false positives are supposed to be fixed in the next release.
# disabled on 02/15/18
Layout/EmptyLinesAroundArguments:
  Enabled: false

Style/OrAssignment:
  Enabled: true

# Should look into re-enableing
# disabled on 11/20/17 - Tanner
Style/DateTime:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

# turn off checking for Carriage return
Layout/EndOfLine:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# Turn off the reversal of comparisons (eg if var == 'compare' vs if 'compare' == var)
Style/YodaCondition:
  Enabled: false

# Use a consistent style for named format string tokens.
# Enforced style: annotated
# Supported styles: annotated/template
Style/FormatStringToken:
  Enabled: false

# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep, IndentationWidth.
# SupportedStyles: case, end
Layout/CaseIndentation:
  IndentOneStep: true
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
# this one doesn't seem to make sense for us:  LJM
Style/ClassAndModuleChildren:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'app/controllers/market/flight_options_controller.rb'

Metrics/LineLength:
  Exclude:
    - 'lib/email_parser/eapis_response/v1/response_formats/response_copy_strings.rb'
    - 'lib/tasks/aircraft_types_load_db.rake'
    - 'app/controllers/portal/inbound_emails_controller.rb'

Metrics/ModuleLength:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Enabled: false

Layout/AlignHash:
  Enabled: false

# Offense count: 2
# Configuration parameters: AllowedVariables.
# LJM not sure how to best move quickbooks global
Style/GlobalVars:
  Enabled: true
  Exclude:
    - 'app/controllers/portal/quickbooks_oauth_sessions_controller.rb'
    - 'config/initializers/quickbooks.rb'
    - 'app/models/trip.rb'

# Cop supports --auto-correct.
# Style/NegatedIf:
#   Enabled: true
#   Include:
#     - 'app/controllers/**'
Style/NegatedIf:
   Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

inherit_from: .rubocop_todo.yml
