default: &default
  adapter: postgresql
  encoding: unicode
  username: connorodoherty
  password:
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: fantasy-baseball-ranker-dev
test:
  <<: *default
  database: connorodoherty
production:
  <<: *default
  database: duel_rank_production
  username: duel_rank
  password: <%= ENV['DATABASE_PASSWORD'] %>